[production]
DEBUG = false
TITLE = 'appconvert'

EXTENSIONS = [
    "appconvert.blueprints.webui:init_app",
]

[development]
DEBUG = true
TITLE = 'appconvert'

EXTENSIONS = [
    "appconvert.blueprints.webui:init_app",
]
