"""refactor(Tokens): Alteração da coluna api_id para aceitar valores nulo

Revision ID: bf993c2df052
Revises: 
Create Date: 2022-03-07 12:02:55.297601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf993c2df052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'id_api',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'id_api',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###
