"""DB Em perfeito estado(eu acho)

Revision ID: d4734cf10bc3
Revises: 
Create Date: 2022-02-14 06:23:07.364297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4734cf10bc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('category')
    op.drop_table('token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=6), nullable=False),
    sa.Column('price', sa.VARCHAR(length=20), nullable=False),
    sa.Column('marketcap', sa.VARCHAR(length=15), nullable=False),
    sa.Column('blockchain', sa.VARCHAR(length=60), nullable=False),
    sa.Column('address', sa.VARCHAR(length=60), nullable=False),
    sa.Column('site', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('token_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('token_id', 'category_id')
    )
    # ### end Alembic commands ###
